apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-uis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-uis
  template:
    metadata:
      labels:
        app: hello-uis
    spec:
      containers:
      - name: hello-uis
        image: dtemir/hello-uis:latest
        ports:
        - containerPort: 8080
